version: 2.1

shared: &shared
  context: org-global

orbs:
  node: circleci/node@5
  browser-tools: circleci/browser-tools@1
  sonarcloud: sonarsource/sonarcloud@1

jobs:
  node:
    parameters:
      install-chrome:
        type: boolean
        default: false
      command:
        type: string
      persist-path:
        type: string
        default: ''
    executor:
      name: node/default
      tag: lts-browsers
    steps:
      - checkout
      - when:
          condition: << parameters.install-chrome >>
          steps:
            - browser-tools/install-chrome
      - node/install-packages
      - run:
          command: << parameters.command >>
      - when:
          condition: << parameters.persist-path >>
          steps:
            - persist_to_workspace:
                root: .
                paths:
                  - << parameters.persist-path >>
  sonar:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - attach_workspace:
          at: .
#      - sonarcloud/scan:
#          sonar_token_variable_name: SONARCLOUD_TOKEN

workflows:
  ci:
    jobs:
      - node:
          <<: *shared
          name: test
          install-chrome: true
          command: npm run test -- --watch=false --browsers=ChromeHeadless
          persist-path: projects/okode/ngx-ui/test-results
      - sonar:
          <<: *shared
          requires:
            - test
      - node:
          <<: *shared
          name: build
          command: npm run build
          persist-path: dist/okode/ngx-ui
          requires:
            - sonar
      - node:
          <<: *shared
          name: storybook
          command: npm run build-storybook
          persist-path: storybook-static
          requires:
            - sonar
