version: 2.1

shared: &shared
  context: org-global

orbs:
  node: circleci/node@5
  browser-tools: circleci/browser-tools@1
  sonarcloud: sonarsource/sonarcloud@1

jobs:
  test:
    executor:
      name: node/default
      tag: lts-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages
      - run:
          command: npm run test -- --watch=false --browsers=ChromeHeadless
      - persist_to_workspace:
          root: .
          paths:
            - sonar-project.properties
            - projects
  sonar:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - attach_workspace:
          at: .
#      - sonarcloud/scan:
#          sonar_token_variable_name: SONARCLOUD_TOKEN

workflows:
  default:
    jobs:
      - test:
          <<: *shared
      - sonar:
          <<: *shared
          requires:
            - test
